# Colors (Nord a bit darker)
[colors.bright]
black = "#4C566A"
blue = "#81A1C1"
cyan = "#8FBCBB"
green = "#A3BE8C"
magenta = "#B48EAD"
red = "#BF616A"
white = "#ECEFF4"
yellow = "#EBCB8B"

[colors.normal]
black = "#3B4252"
blue = "#81A1C1"
cyan = "#88C0D0"
green = "#A3BE8C"
magenta = "#B48EAD"
red = "#BF616A"
white = "#E5E9F0"
yellow = "#EBCB8B"

[colors.primary]
background = "#232730"
foreground = "#D8DEE9"

[font]
size = 10.5

[font.bold]
#family = "Fira Code"
family = "Jetbrains Mono"
style = "Bold"

[font.italic]
#family = "Fira Code"
family = "Jetbrains Mono"
style = "Italic"

[font.normal]
#family = "Fira Code"
family = "Jetbrains Mono"
style = "Light"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"
